// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigrationIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractVersion(Vec<Integer>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigrationVersion {
    pub major: Integer,
    pub minor: Integer,
    pub patch: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MigrationState {
    Enabled,
    Disabled,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub migration: MigrationIdentifier,
    pub state: MigrationState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRange {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum BlockReason {
    Unsafe,
    Superseded,
    NotReviewed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Block {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: BlockReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Query {
    All,
    Component(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyEntry {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub state: MigrationState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyReported(Vec<PolicyEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CatalogueRejectionReason {
    UnknownMigration,
    AlreadyRegistered,
    NotAllowed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRejected {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: CatalogueRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VersionLabel(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectorVersion {
    pub label: VersionLabel,
    pub contract_version: ContractVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ForceReason {
    OperatorOverride,
    MarkerMismatchAccepted,
    EmergencyRecovery,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RollbackReason {
    PostCutoverFailure,
    OperatorOverride,
    RecoveryDrill,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum QuarantineReason {
    FailedUpgrade,
    SuspectState,
    OperatorHold,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForceFlip {
    pub component: ComponentName,
    pub current_version: SelectorVersion,
    pub target_version: SelectorVersion,
    pub reason: ForceReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rollback {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
    pub restore_version: SelectorVersion,
    pub reason: RollbackReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantine {
    pub component: ComponentName,
    pub version: SelectorVersion,
    pub reason: QuarantineReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForcedFlip {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolledBack {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantined {
    pub component: ComponentName,
    pub version: SelectorVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SelectorRejectionReason {
    UnknownComponent,
    UnknownVersion,
    NotAllowed,
    AlreadyQuarantined,
    NotQuarantined,
    VersionQuarantined,
    HandoverRejected,
    UpgradeSocketUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejected {
    pub component: ComponentName,
    pub reason: SelectorRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotBuiltYet,
    IntegrationNotLanded,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Register(Registration),
    Allow(PolicyRange),
    Block(Block),
    Query(Query),
    ForceFlip(ForceFlip),
    Rollback(Rollback),
    Quarantine(Quarantine),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Registered(Registration),
    Allowed(PolicyRange),
    Blocked(Block),
    PolicyReported(PolicyReported),
    PolicyRejected(PolicyRejected),
    FlipForced(ForcedFlip),
    RolledBack(RolledBack),
    Quarantined(Quarantined),
    Rejected(Rejected),
    RequestUnimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl ComponentName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ComponentName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ComponentName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ComponentName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl MigrationIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MigrationIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for MigrationIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for MigrationIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for MigrationIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ContractVersion {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Integer>> for ContractVersion {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PolicyReported {
    pub fn new(payload: Vec<PolicyEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<PolicyEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<PolicyEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<PolicyEntry>> for PolicyReported {
    fn from(payload: Vec<PolicyEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl VersionLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for VersionLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for VersionLabel {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for VersionLabel {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for VersionLabel {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn component(payload: String) -> Self {
        Self::Component(ComponentName::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn register(payload: Registration) -> Self {
        Self::Register(payload)
    }
    pub fn allow(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }
    pub fn block(payload: Block) -> Self {
        Self::Block(payload)
    }
    pub fn query(payload: Query) -> Self {
        Self::Query(payload)
    }
    pub fn force_flip(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }
    pub fn rollback(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }
    pub fn quarantine(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn registered(payload: Registration) -> Self {
        Self::Registered(payload)
    }
    pub fn allowed(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }
    pub fn blocked(payload: Block) -> Self {
        Self::Blocked(payload)
    }
    pub fn policy_reported(payload: Vec<PolicyEntry>) -> Self {
        Self::PolicyReported(PolicyReported::new(payload))
    }
    pub fn policy_rejected(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
    pub fn flip_forced(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }
    pub fn rolled_back(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }
    pub fn quarantined(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }
    pub fn rejected(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

#[rustfmt::skip]
impl From<ComponentName> for Query {
    fn from(payload: ComponentName) -> Self {
        Self::Component(payload)
    }
}

#[rustfmt::skip]
impl From<Registration> for Input {
    fn from(payload: Registration) -> Self {
        Self::Register(payload)
    }
}

#[rustfmt::skip]
impl From<PolicyRange> for Input {
    fn from(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }
}

#[rustfmt::skip]
impl From<Block> for Input {
    fn from(payload: Block) -> Self {
        Self::Block(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<ForceFlip> for Input {
    fn from(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }
}

#[rustfmt::skip]
impl From<Rollback> for Input {
    fn from(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }
}

#[rustfmt::skip]
impl From<Quarantine> for Input {
    fn from(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

#[rustfmt::skip]
impl From<Registration> for Output {
    fn from(payload: Registration) -> Self {
        Self::Registered(payload)
    }
}

#[rustfmt::skip]
impl From<PolicyRange> for Output {
    fn from(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }
}

#[rustfmt::skip]
impl From<Block> for Output {
    fn from(payload: Block) -> Self {
        Self::Blocked(payload)
    }
}

#[rustfmt::skip]
impl From<PolicyReported> for Output {
    fn from(payload: PolicyReported) -> Self {
        Self::PolicyReported(payload)
    }
}

#[rustfmt::skip]
impl From<PolicyRejected> for Output {
    fn from(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ForcedFlip> for Output {
    fn from(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }
}

#[rustfmt::skip]
impl From<RolledBack> for Output {
    fn from(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }
}

#[rustfmt::skip]
impl From<Quarantined> for Output {
    fn from(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }
}

#[rustfmt::skip]
impl From<Rejected> for Output {
    fn from(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_REGISTER: u64 = 0x0000000000000000;
    pub const INPUT_ALLOW: u64 = 0x0001000000000000;
    pub const INPUT_BLOCK: u64 = 0x0002000000000000;
    pub const INPUT_QUERY: u64 = 0x0003000000000000;
    pub const INPUT_FORCE_FLIP: u64 = 0x0004000000000000;
    pub const INPUT_ROLLBACK: u64 = 0x0005000000000000;
    pub const INPUT_QUARANTINE: u64 = 0x0006000000000000;
    pub const OUTPUT_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_ALLOWED: u64 = 0x0101000000000000;
    pub const OUTPUT_BLOCKED: u64 = 0x0102000000000000;
    pub const OUTPUT_POLICY_REPORTED: u64 = 0x0103000000000000;
    pub const OUTPUT_POLICY_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_FLIP_FORCED: u64 = 0x0105000000000000;
    pub const OUTPUT_ROLLED_BACK: u64 = 0x0106000000000000;
    pub const OUTPUT_QUARANTINED: u64 = 0x0107000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0108000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0109000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Register,
    Allow,
    Block,
    Query,
    ForceFlip,
    Rollback,
    Quarantine,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Registered,
    Allowed,
    Blocked,
    PolicyReported,
    PolicyRejected,
    FlipForced,
    RolledBack,
    Quarantined,
    Rejected,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Register(_) => InputRoute::Register,
            Self::Allow(_) => InputRoute::Allow,
            Self::Block(_) => InputRoute::Block,
            Self::Query(_) => InputRoute::Query,
            Self::ForceFlip(_) => InputRoute::ForceFlip,
            Self::Rollback(_) => InputRoute::Rollback,
            Self::Quarantine(_) => InputRoute::Quarantine,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Register(_) => short_header::INPUT_REGISTER,
            Self::Allow(_) => short_header::INPUT_ALLOW,
            Self::Block(_) => short_header::INPUT_BLOCK,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::ForceFlip(_) => short_header::INPUT_FORCE_FLIP,
            Self::Rollback(_) => short_header::INPUT_ROLLBACK,
            Self::Quarantine(_) => short_header::INPUT_QUARANTINE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER => Ok(InputRoute::Register),
            short_header::INPUT_ALLOW => Ok(InputRoute::Allow),
            short_header::INPUT_BLOCK => Ok(InputRoute::Block),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_FORCE_FLIP => Ok(InputRoute::ForceFlip),
            short_header::INPUT_ROLLBACK => Ok(InputRoute::Rollback),
            short_header::INPUT_QUARANTINE => Ok(InputRoute::Quarantine),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Registered(_) => OutputRoute::Registered,
            Self::Allowed(_) => OutputRoute::Allowed,
            Self::Blocked(_) => OutputRoute::Blocked,
            Self::PolicyReported(_) => OutputRoute::PolicyReported,
            Self::PolicyRejected(_) => OutputRoute::PolicyRejected,
            Self::FlipForced(_) => OutputRoute::FlipForced,
            Self::RolledBack(_) => OutputRoute::RolledBack,
            Self::Quarantined(_) => OutputRoute::Quarantined,
            Self::Rejected(_) => OutputRoute::Rejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Registered(_) => short_header::OUTPUT_REGISTERED,
            Self::Allowed(_) => short_header::OUTPUT_ALLOWED,
            Self::Blocked(_) => short_header::OUTPUT_BLOCKED,
            Self::PolicyReported(_) => short_header::OUTPUT_POLICY_REPORTED,
            Self::PolicyRejected(_) => short_header::OUTPUT_POLICY_REJECTED,
            Self::FlipForced(_) => short_header::OUTPUT_FLIP_FORCED,
            Self::RolledBack(_) => short_header::OUTPUT_ROLLED_BACK,
            Self::Quarantined(_) => short_header::OUTPUT_QUARANTINED,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_REGISTERED => Ok(OutputRoute::Registered),
            short_header::OUTPUT_ALLOWED => Ok(OutputRoute::Allowed),
            short_header::OUTPUT_BLOCKED => Ok(OutputRoute::Blocked),
            short_header::OUTPUT_POLICY_REPORTED => Ok(OutputRoute::PolicyReported),
            short_header::OUTPUT_POLICY_REJECTED => Ok(OutputRoute::PolicyRejected),
            short_header::OUTPUT_FLIP_FORCED => Ok(OutputRoute::FlipForced),
            short_header::OUTPUT_ROLLED_BACK => Ok(OutputRoute::RolledBack),
            short_header::OUTPUT_QUARANTINED => Ok(OutputRoute::Quarantined),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::RequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Register",
        "Allow",
        "Block",
        "Query",
        "ForceFlip",
        "Rollback",
        "Quarantine",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
