// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type ComponentName = String;

pub type MigrationIdentifier = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractVersion(pub Vec<Integer>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigrationVersion {
    pub major: Integer,
    pub minor: Integer,
    pub patch: Integer,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MigrationState {
    Enabled,
    Disabled,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub migration: MigrationIdentifier,
    pub state: MigrationState,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRange {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum BlockReason {
    Unsafe,
    Superseded,
    NotReviewed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Block {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: BlockReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Query {
    All,
    Component(ComponentName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyEntry {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub state: MigrationState,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyReported(pub Vec<PolicyEntry>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CatalogueRejectionReason {
    UnknownMigration,
    AlreadyRegistered,
    NotAllowed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRejected {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: CatalogueRejectionReason,
}

pub type VersionLabel = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectorVersion {
    pub label: VersionLabel,
    pub contract_version: ContractVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ForceReason {
    OperatorOverride,
    MarkerMismatchAccepted,
    EmergencyRecovery,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RollbackReason {
    PostCutoverFailure,
    OperatorOverride,
    RecoveryDrill,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum QuarantineReason {
    FailedUpgrade,
    SuspectState,
    OperatorHold,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForceFlip {
    pub component: ComponentName,
    pub current_version: SelectorVersion,
    pub target_version: SelectorVersion,
    pub reason: ForceReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rollback {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
    pub restore_version: SelectorVersion,
    pub reason: RollbackReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantine {
    pub component: ComponentName,
    pub version: SelectorVersion,
    pub reason: QuarantineReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForcedFlip {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolledBack {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantined {
    pub component: ComponentName,
    pub version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SelectorRejectionReason {
    UnknownComponent,
    UnknownVersion,
    NotAllowed,
    AlreadyQuarantined,
    NotQuarantined,
    VersionQuarantined,
    HandoverRejected,
    UpgradeSocketUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejected {
    pub component: ComponentName,
    pub reason: SelectorRejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotBuiltYet,
    IntegrationNotLanded,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(pub UnimplementedReason);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Register(Registration),
    Allow(PolicyRange),
    Block(Block),
    Query(Query),
    ForceFlip(ForceFlip),
    Rollback(Rollback),
    Quarantine(Quarantine),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Registered(Registration),
    Allowed(PolicyRange),
    Blocked(Block),
    PolicyReported(PolicyReported),
    PolicyRejected(PolicyRejected),
    FlipForced(ForcedFlip),
    RolledBack(RolledBack),
    Quarantined(Quarantined),
    Rejected(Rejected),
    RequestUnimplemented(RequestUnimplemented),
}

impl ContractVersion {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}

impl From<Vec<Integer>> for ContractVersion {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

impl PolicyReported {
    pub fn new(payload: Vec<PolicyEntry>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<PolicyEntry> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<PolicyEntry> {
        self.0
    }
}

impl From<Vec<PolicyEntry>> for PolicyReported {
    fn from(payload: Vec<PolicyEntry>) -> Self {
        Self::new(payload)
    }
}

impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }

    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}

impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

impl Query {
    pub fn component(payload: ComponentName) -> Self {
        Self::Component(payload)
    }
}

impl Input {
    pub fn register(payload: Registration) -> Self {
        Self::Register(payload)
    }

    pub fn allow(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }

    pub fn block(payload: Block) -> Self {
        Self::Block(payload)
    }

    pub fn query(payload: Query) -> Self {
        Self::Query(payload)
    }

    pub fn force_flip(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }

    pub fn rollback(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }

    pub fn quarantine(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl Output {
    pub fn registered(payload: Registration) -> Self {
        Self::Registered(payload)
    }

    pub fn allowed(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }

    pub fn blocked(payload: Block) -> Self {
        Self::Blocked(payload)
    }

    pub fn policy_reported(payload: Vec<PolicyEntry>) -> Self {
        Self::PolicyReported(PolicyReported::new(payload))
    }

    pub fn policy_rejected(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }

    pub fn flip_forced(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }

    pub fn rolled_back(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }

    pub fn quarantined(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }

    pub fn rejected(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }

    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

impl From<Registration> for Input {
    fn from(payload: Registration) -> Self {
        Self::Register(payload)
    }
}

impl From<PolicyRange> for Input {
    fn from(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }
}

impl From<Block> for Input {
    fn from(payload: Block) -> Self {
        Self::Block(payload)
    }
}

impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

impl From<ForceFlip> for Input {
    fn from(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }
}

impl From<Rollback> for Input {
    fn from(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }
}

impl From<Quarantine> for Input {
    fn from(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl From<Registration> for Output {
    fn from(payload: Registration) -> Self {
        Self::Registered(payload)
    }
}

impl From<PolicyRange> for Output {
    fn from(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }
}

impl From<Block> for Output {
    fn from(payload: Block) -> Self {
        Self::Blocked(payload)
    }
}

impl From<PolicyReported> for Output {
    fn from(payload: PolicyReported) -> Self {
        Self::PolicyReported(payload)
    }
}

impl From<PolicyRejected> for Output {
    fn from(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
}

impl From<ForcedFlip> for Output {
    fn from(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }
}

impl From<RolledBack> for Output {
    fn from(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }
}

impl From<Quarantined> for Output {
    fn from(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }
}

impl From<Rejected> for Output {
    fn from(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
}

impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[cfg(feature = "nota-text")]
impl ContractVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MigrationVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MigrationState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Registration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyRange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl BlockReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Block {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyReported {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CatalogueRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SelectorVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForceReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RollbackReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl QuarantineReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForceFlip {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rollback {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Quarantine {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForcedFlip {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RolledBack {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Quarantined {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SelectorRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_REGISTER: u64 = 0x0000000000000000;
    pub const INPUT_ALLOW: u64 = 0x0001000000000000;
    pub const INPUT_BLOCK: u64 = 0x0002000000000000;
    pub const INPUT_QUERY: u64 = 0x0003000000000000;
    pub const INPUT_FORCE_FLIP: u64 = 0x0004000000000000;
    pub const INPUT_ROLLBACK: u64 = 0x0005000000000000;
    pub const INPUT_QUARANTINE: u64 = 0x0006000000000000;
    pub const OUTPUT_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_ALLOWED: u64 = 0x0101000000000000;
    pub const OUTPUT_BLOCKED: u64 = 0x0102000000000000;
    pub const OUTPUT_POLICY_REPORTED: u64 = 0x0103000000000000;
    pub const OUTPUT_POLICY_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_FLIP_FORCED: u64 = 0x0105000000000000;
    pub const OUTPUT_ROLLED_BACK: u64 = 0x0106000000000000;
    pub const OUTPUT_QUARANTINED: u64 = 0x0107000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0108000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0109000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    Register,
    Allow,
    Block,
    Query,
    ForceFlip,
    Rollback,
    Quarantine,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    Registered,
    Allowed,
    Blocked,
    PolicyReported,
    PolicyRejected,
    FlipForced,
    RolledBack,
    Quarantined,
    Rejected,
    RequestUnimplemented,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Register(_) => InputRoute::Register,
            Self::Allow(_) => InputRoute::Allow,
            Self::Block(_) => InputRoute::Block,
            Self::Query(_) => InputRoute::Query,
            Self::ForceFlip(_) => InputRoute::ForceFlip,
            Self::Rollback(_) => InputRoute::Rollback,
            Self::Quarantine(_) => InputRoute::Quarantine,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Register(_) => short_header::INPUT_REGISTER,
            Self::Allow(_) => short_header::INPUT_ALLOW,
            Self::Block(_) => short_header::INPUT_BLOCK,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::ForceFlip(_) => short_header::INPUT_FORCE_FLIP,
            Self::Rollback(_) => short_header::INPUT_ROLLBACK,
            Self::Quarantine(_) => short_header::INPUT_QUARANTINE,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER => Ok(InputRoute::Register),
            short_header::INPUT_ALLOW => Ok(InputRoute::Allow),
            short_header::INPUT_BLOCK => Ok(InputRoute::Block),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_FORCE_FLIP => Ok(InputRoute::ForceFlip),
            short_header::INPUT_ROLLBACK => Ok(InputRoute::Rollback),
            short_header::INPUT_QUARANTINE => Ok(InputRoute::Quarantine),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Registered(_) => OutputRoute::Registered,
            Self::Allowed(_) => OutputRoute::Allowed,
            Self::Blocked(_) => OutputRoute::Blocked,
            Self::PolicyReported(_) => OutputRoute::PolicyReported,
            Self::PolicyRejected(_) => OutputRoute::PolicyRejected,
            Self::FlipForced(_) => OutputRoute::FlipForced,
            Self::RolledBack(_) => OutputRoute::RolledBack,
            Self::Quarantined(_) => OutputRoute::Quarantined,
            Self::Rejected(_) => OutputRoute::Rejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Registered(_) => short_header::OUTPUT_REGISTERED,
            Self::Allowed(_) => short_header::OUTPUT_ALLOWED,
            Self::Blocked(_) => short_header::OUTPUT_BLOCKED,
            Self::PolicyReported(_) => short_header::OUTPUT_POLICY_REPORTED,
            Self::PolicyRejected(_) => short_header::OUTPUT_POLICY_REJECTED,
            Self::FlipForced(_) => short_header::OUTPUT_FLIP_FORCED,
            Self::RolledBack(_) => short_header::OUTPUT_ROLLED_BACK,
            Self::Quarantined(_) => short_header::OUTPUT_QUARANTINED,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_REGISTERED => Ok(OutputRoute::Registered),
            short_header::OUTPUT_ALLOWED => Ok(OutputRoute::Allowed),
            short_header::OUTPUT_BLOCKED => Ok(OutputRoute::Blocked),
            short_header::OUTPUT_POLICY_REPORTED => Ok(OutputRoute::PolicyReported),
            short_header::OUTPUT_POLICY_REJECTED => Ok(OutputRoute::PolicyRejected),
            short_header::OUTPUT_FLIP_FORCED => Ok(OutputRoute::FlipForced),
            short_header::OUTPUT_ROLLED_BACK => Ok(OutputRoute::RolledBack),
            short_header::OUTPUT_QUARANTINED => Ok(OutputRoute::Quarantined),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => Ok(OutputRoute::RequestUnimplemented),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

