// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type ComponentName = String;

pub type MigrationIdentifier = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ContractVersion(pub Vec<Integer>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MigrationVersion {
    pub major: Integer,
    pub minor: Integer,
    pub patch: Integer,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MigrationState {
    Enabled,
    Disabled,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub migration: MigrationIdentifier,
    pub state: MigrationState,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRange {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum BlockReason {
    Unsafe,
    Superseded,
    NotReviewed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Block {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: BlockReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Query {
    All,
    Component(ComponentName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyEntry {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub state: MigrationState,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyReported(pub Vec<PolicyEntry>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CatalogueRejectionReason {
    UnknownMigration,
    AlreadyRegistered,
    NotAllowed,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicyRejected {
    pub component: ComponentName,
    pub source: MigrationVersion,
    pub target: MigrationVersion,
    pub reason: CatalogueRejectionReason,
}

pub type VersionLabel = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SelectorVersion {
    pub label: VersionLabel,
    pub contract_version: ContractVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ForceReason {
    OperatorOverride,
    MarkerMismatchAccepted,
    EmergencyRecovery,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RollbackReason {
    PostCutoverFailure,
    OperatorOverride,
    RecoveryDrill,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum QuarantineReason {
    FailedUpgrade,
    SuspectState,
    OperatorHold,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForceFlip {
    pub component: ComponentName,
    pub current_version: SelectorVersion,
    pub target_version: SelectorVersion,
    pub reason: ForceReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rollback {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
    pub restore_version: SelectorVersion,
    pub reason: RollbackReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantine {
    pub component: ComponentName,
    pub version: SelectorVersion,
    pub reason: QuarantineReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ForcedFlip {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolledBack {
    pub component: ComponentName,
    pub active_version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Quarantined {
    pub component: ComponentName,
    pub version: SelectorVersion,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SelectorRejectionReason {
    UnknownComponent,
    UnknownVersion,
    NotAllowed,
    AlreadyQuarantined,
    NotQuarantined,
    VersionQuarantined,
    HandoverRejected,
    UpgradeSocketUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Rejected {
    pub component: ComponentName,
    pub reason: SelectorRejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotBuiltYet,
    IntegrationNotLanded,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(pub UnimplementedReason);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(Input),
    SemaWriteCompleted(SemaWriteOutput),
    SemaReadCompleted(SemaReadOutput),
    EffectCompleted(NexusEffectResult),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    CommandSemaWrite(SemaWriteInput),
    CommandSemaRead(SemaReadInput),
    ReplyToSignal(Output),
    CommandEffect(NexusEffectCommand),
    Continue(NexusWork),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    NotifySelector(ForceFlip),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    SelectorNotified(ForcedFlip),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteInput {
    Register(Registration),
    Allow(PolicyRange),
    Block(Block),
    ForceFlip(ForceFlip),
    Rollback(Rollback),
    Quarantine(Quarantine),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadInput {
    Query(Query),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaWriteOutput {
    Registered(Registration),
    Allowed(PolicyRange),
    Blocked(Block),
    PolicyRejected(PolicyRejected),
    FlipForced(ForcedFlip),
    RolledBack(RolledBack),
    Quarantined(Quarantined),
    Rejected(Rejected),
    RequestUnimplemented(RequestUnimplemented),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SemaReadOutput {
    PolicyReported(PolicyReported),
    PolicyRejected(PolicyRejected),
    RequestUnimplemented(RequestUnimplemented),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Register(Registration),
    Allow(PolicyRange),
    Block(Block),
    Query(Query),
    ForceFlip(ForceFlip),
    Rollback(Rollback),
    Quarantine(Quarantine),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Registered(Registration),
    Allowed(PolicyRange),
    Blocked(Block),
    PolicyReported(PolicyReported),
    PolicyRejected(PolicyRejected),
    FlipForced(ForcedFlip),
    RolledBack(RolledBack),
    Quarantined(Quarantined),
    Rejected(Rejected),
    RequestUnimplemented(RequestUnimplemented),
}

impl ContractVersion {
    pub fn new(payload: Vec<Integer>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<Integer> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<Integer> {
        self.0
    }
}

impl From<Vec<Integer>> for ContractVersion {
    fn from(payload: Vec<Integer>) -> Self {
        Self::new(payload)
    }
}

impl PolicyReported {
    pub fn new(payload: Vec<PolicyEntry>) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &Vec<PolicyEntry> {
        &self.0
    }

    pub fn into_payload(self) -> Vec<PolicyEntry> {
        self.0
    }
}

impl From<Vec<PolicyEntry>> for PolicyReported {
    fn from(payload: Vec<PolicyEntry>) -> Self {
        Self::new(payload)
    }
}

impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }

    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}

impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

impl Query {
    pub fn component(payload: ComponentName) -> Self {
        Self::Component(payload)
    }
}

impl NexusWork {
    pub fn signal_arrived(payload: Input) -> Self {
        Self::SignalArrived(payload)
    }

    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }

    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }

    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl NexusAction {
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }

    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }

    pub fn reply_to_signal(payload: Output) -> Self {
        Self::ReplyToSignal(payload)
    }

    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }

    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

impl NexusEffectCommand {
    pub fn notify_selector(payload: ForceFlip) -> Self {
        Self::NotifySelector(payload)
    }
}

impl NexusEffectResult {
    pub fn selector_notified(payload: ForcedFlip) -> Self {
        Self::SelectorNotified(payload)
    }
}

impl SemaWriteInput {
    pub fn register(payload: Registration) -> Self {
        Self::Register(payload)
    }

    pub fn allow(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }

    pub fn block(payload: Block) -> Self {
        Self::Block(payload)
    }

    pub fn force_flip(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }

    pub fn rollback(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }

    pub fn quarantine(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl SemaReadInput {
    pub fn query(payload: Query) -> Self {
        Self::Query(payload)
    }
}

impl SemaWriteOutput {
    pub fn registered(payload: Registration) -> Self {
        Self::Registered(payload)
    }

    pub fn allowed(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }

    pub fn blocked(payload: Block) -> Self {
        Self::Blocked(payload)
    }

    pub fn policy_rejected(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }

    pub fn flip_forced(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }

    pub fn rolled_back(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }

    pub fn quarantined(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }

    pub fn rejected(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }

    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

impl SemaReadOutput {
    pub fn policy_reported(payload: Vec<PolicyEntry>) -> Self {
        Self::PolicyReported(PolicyReported::new(payload))
    }

    pub fn policy_rejected(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }

    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

impl Input {
    pub fn register(payload: Registration) -> Self {
        Self::Register(payload)
    }

    pub fn allow(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }

    pub fn block(payload: Block) -> Self {
        Self::Block(payload)
    }

    pub fn query(payload: Query) -> Self {
        Self::Query(payload)
    }

    pub fn force_flip(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }

    pub fn rollback(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }

    pub fn quarantine(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl Output {
    pub fn registered(payload: Registration) -> Self {
        Self::Registered(payload)
    }

    pub fn allowed(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }

    pub fn blocked(payload: Block) -> Self {
        Self::Blocked(payload)
    }

    pub fn policy_reported(payload: Vec<PolicyEntry>) -> Self {
        Self::PolicyReported(PolicyReported::new(payload))
    }

    pub fn policy_rejected(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }

    pub fn flip_forced(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }

    pub fn rolled_back(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }

    pub fn quarantined(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }

    pub fn rejected(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }

    pub fn request_unimplemented(payload: UnimplementedReason) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

impl From<Input> for NexusWork {
    fn from(payload: Input) -> Self {
        Self::SignalArrived(payload)
    }
}

impl From<SemaWriteOutput> for NexusWork {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

impl From<SemaReadOutput> for NexusWork {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

impl From<NexusEffectResult> for NexusWork {
    fn from(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

impl From<SemaWriteInput> for NexusAction {
    fn from(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

impl From<SemaReadInput> for NexusAction {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

impl From<Output> for NexusAction {
    fn from(payload: Output) -> Self {
        Self::ReplyToSignal(payload)
    }
}

impl From<NexusEffectCommand> for NexusAction {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

impl From<NexusWork> for NexusAction {
    fn from(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

impl From<ForceFlip> for NexusEffectCommand {
    fn from(payload: ForceFlip) -> Self {
        Self::NotifySelector(payload)
    }
}

impl From<ForcedFlip> for NexusEffectResult {
    fn from(payload: ForcedFlip) -> Self {
        Self::SelectorNotified(payload)
    }
}

impl From<Registration> for SemaWriteInput {
    fn from(payload: Registration) -> Self {
        Self::Register(payload)
    }
}

impl From<PolicyRange> for SemaWriteInput {
    fn from(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }
}

impl From<Block> for SemaWriteInput {
    fn from(payload: Block) -> Self {
        Self::Block(payload)
    }
}

impl From<ForceFlip> for SemaWriteInput {
    fn from(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }
}

impl From<Rollback> for SemaWriteInput {
    fn from(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }
}

impl From<Quarantine> for SemaWriteInput {
    fn from(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl From<Query> for SemaReadInput {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

impl From<Registration> for SemaWriteOutput {
    fn from(payload: Registration) -> Self {
        Self::Registered(payload)
    }
}

impl From<PolicyRange> for SemaWriteOutput {
    fn from(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }
}

impl From<Block> for SemaWriteOutput {
    fn from(payload: Block) -> Self {
        Self::Blocked(payload)
    }
}

impl From<PolicyRejected> for SemaWriteOutput {
    fn from(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
}

impl From<ForcedFlip> for SemaWriteOutput {
    fn from(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }
}

impl From<RolledBack> for SemaWriteOutput {
    fn from(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }
}

impl From<Quarantined> for SemaWriteOutput {
    fn from(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }
}

impl From<Rejected> for SemaWriteOutput {
    fn from(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
}

impl From<RequestUnimplemented> for SemaWriteOutput {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

impl From<PolicyReported> for SemaReadOutput {
    fn from(payload: PolicyReported) -> Self {
        Self::PolicyReported(payload)
    }
}

impl From<PolicyRejected> for SemaReadOutput {
    fn from(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
}

impl From<RequestUnimplemented> for SemaReadOutput {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

impl From<Registration> for Input {
    fn from(payload: Registration) -> Self {
        Self::Register(payload)
    }
}

impl From<PolicyRange> for Input {
    fn from(payload: PolicyRange) -> Self {
        Self::Allow(payload)
    }
}

impl From<Block> for Input {
    fn from(payload: Block) -> Self {
        Self::Block(payload)
    }
}

impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

impl From<ForceFlip> for Input {
    fn from(payload: ForceFlip) -> Self {
        Self::ForceFlip(payload)
    }
}

impl From<Rollback> for Input {
    fn from(payload: Rollback) -> Self {
        Self::Rollback(payload)
    }
}

impl From<Quarantine> for Input {
    fn from(payload: Quarantine) -> Self {
        Self::Quarantine(payload)
    }
}

impl From<Registration> for Output {
    fn from(payload: Registration) -> Self {
        Self::Registered(payload)
    }
}

impl From<PolicyRange> for Output {
    fn from(payload: PolicyRange) -> Self {
        Self::Allowed(payload)
    }
}

impl From<Block> for Output {
    fn from(payload: Block) -> Self {
        Self::Blocked(payload)
    }
}

impl From<PolicyReported> for Output {
    fn from(payload: PolicyReported) -> Self {
        Self::PolicyReported(payload)
    }
}

impl From<PolicyRejected> for Output {
    fn from(payload: PolicyRejected) -> Self {
        Self::PolicyRejected(payload)
    }
}

impl From<ForcedFlip> for Output {
    fn from(payload: ForcedFlip) -> Self {
        Self::FlipForced(payload)
    }
}

impl From<RolledBack> for Output {
    fn from(payload: RolledBack) -> Self {
        Self::RolledBack(payload)
    }
}

impl From<Quarantined> for Output {
    fn from(payload: Quarantined) -> Self {
        Self::Quarantined(payload)
    }
}

impl From<Rejected> for Output {
    fn from(payload: Rejected) -> Self {
        Self::Rejected(payload)
    }
}

impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[cfg(feature = "nota-text")]
impl ContractVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MigrationVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl MigrationState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Registration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyRange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl BlockReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Block {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Query {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyReported {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl CatalogueRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicyRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SelectorVersion {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForceReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RollbackReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl QuarantineReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForceFlip {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rollback {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Quarantine {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ForcedFlip {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RolledBack {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Quarantined {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SelectorRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Rejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaWriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SemaReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_REGISTER: u64 = 0x0000000000000000;
    pub const INPUT_ALLOW: u64 = 0x0001000000000000;
    pub const INPUT_BLOCK: u64 = 0x0002000000000000;
    pub const INPUT_QUERY: u64 = 0x0003000000000000;
    pub const INPUT_FORCE_FLIP: u64 = 0x0004000000000000;
    pub const INPUT_ROLLBACK: u64 = 0x0005000000000000;
    pub const INPUT_QUARANTINE: u64 = 0x0006000000000000;
    pub const OUTPUT_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_ALLOWED: u64 = 0x0101000000000000;
    pub const OUTPUT_BLOCKED: u64 = 0x0102000000000000;
    pub const OUTPUT_POLICY_REPORTED: u64 = 0x0103000000000000;
    pub const OUTPUT_POLICY_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_FLIP_FORCED: u64 = 0x0105000000000000;
    pub const OUTPUT_ROLLED_BACK: u64 = 0x0106000000000000;
    pub const OUTPUT_QUARANTINED: u64 = 0x0107000000000000;
    pub const OUTPUT_REJECTED: u64 = 0x0108000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0109000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    Register,
    Allow,
    Block,
    Query,
    ForceFlip,
    Rollback,
    Quarantine,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    Registered,
    Allowed,
    Blocked,
    PolicyReported,
    PolicyRejected,
    FlipForced,
    RolledBack,
    Quarantined,
    Rejected,
    RequestUnimplemented,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Register(_) => InputRoute::Register,
            Self::Allow(_) => InputRoute::Allow,
            Self::Block(_) => InputRoute::Block,
            Self::Query(_) => InputRoute::Query,
            Self::ForceFlip(_) => InputRoute::ForceFlip,
            Self::Rollback(_) => InputRoute::Rollback,
            Self::Quarantine(_) => InputRoute::Quarantine,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Register(_) => short_header::INPUT_REGISTER,
            Self::Allow(_) => short_header::INPUT_ALLOW,
            Self::Block(_) => short_header::INPUT_BLOCK,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::ForceFlip(_) => short_header::INPUT_FORCE_FLIP,
            Self::Rollback(_) => short_header::INPUT_ROLLBACK,
            Self::Quarantine(_) => short_header::INPUT_QUARANTINE,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER => Ok(InputRoute::Register),
            short_header::INPUT_ALLOW => Ok(InputRoute::Allow),
            short_header::INPUT_BLOCK => Ok(InputRoute::Block),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_FORCE_FLIP => Ok(InputRoute::ForceFlip),
            short_header::INPUT_ROLLBACK => Ok(InputRoute::Rollback),
            short_header::INPUT_QUARANTINE => Ok(InputRoute::Quarantine),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Registered(_) => OutputRoute::Registered,
            Self::Allowed(_) => OutputRoute::Allowed,
            Self::Blocked(_) => OutputRoute::Blocked,
            Self::PolicyReported(_) => OutputRoute::PolicyReported,
            Self::PolicyRejected(_) => OutputRoute::PolicyRejected,
            Self::FlipForced(_) => OutputRoute::FlipForced,
            Self::RolledBack(_) => OutputRoute::RolledBack,
            Self::Quarantined(_) => OutputRoute::Quarantined,
            Self::Rejected(_) => OutputRoute::Rejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Registered(_) => short_header::OUTPUT_REGISTERED,
            Self::Allowed(_) => short_header::OUTPUT_ALLOWED,
            Self::Blocked(_) => short_header::OUTPUT_BLOCKED,
            Self::PolicyReported(_) => short_header::OUTPUT_POLICY_REPORTED,
            Self::PolicyRejected(_) => short_header::OUTPUT_POLICY_REJECTED,
            Self::FlipForced(_) => short_header::OUTPUT_FLIP_FORCED,
            Self::RolledBack(_) => short_header::OUTPUT_ROLLED_BACK,
            Self::Quarantined(_) => short_header::OUTPUT_QUARANTINED,
            Self::Rejected(_) => short_header::OUTPUT_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_REGISTERED => Ok(OutputRoute::Registered),
            short_header::OUTPUT_ALLOWED => Ok(OutputRoute::Allowed),
            short_header::OUTPUT_BLOCKED => Ok(OutputRoute::Blocked),
            short_header::OUTPUT_POLICY_REPORTED => Ok(OutputRoute::PolicyReported),
            short_header::OUTPUT_POLICY_REJECTED => Ok(OutputRoute::PolicyRejected),
            short_header::OUTPUT_FLIP_FORCED => Ok(OutputRoute::FlipForced),
            short_header::OUTPUT_ROLLED_BACK => Ok(OutputRoute::RolledBack),
            short_header::OUTPUT_QUARANTINED => Ok(OutputRoute::Quarantined),
            short_header::OUTPUT_REJECTED => Ok(OutputRoute::Rejected),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => Ok(OutputRoute::RequestUnimplemented),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusActionRoute {
    CommandSemaWrite,
    CommandSemaRead,
    ReplyToSignal,
    CommandEffect,
    Continue,
}

impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteInputRoute {
    Register,
    Allow,
    Block,
    ForceFlip,
    Rollback,
    Quarantine,
}

impl SemaWriteInput {
    pub fn route(&self) -> SemaWriteInputRoute {
        match self {
            Self::Register(_) => SemaWriteInputRoute::Register,
            Self::Allow(_) => SemaWriteInputRoute::Allow,
            Self::Block(_) => SemaWriteInputRoute::Block,
            Self::ForceFlip(_) => SemaWriteInputRoute::ForceFlip,
            Self::Rollback(_) => SemaWriteInputRoute::Rollback,
            Self::Quarantine(_) => SemaWriteInputRoute::Quarantine,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadInputRoute {
    Query,
}

impl SemaReadInput {
    pub fn route(&self) -> SemaReadInputRoute {
        match self {
            Self::Query(_) => SemaReadInputRoute::Query,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaWriteOutputRoute {
    Registered,
    Allowed,
    Blocked,
    PolicyRejected,
    FlipForced,
    RolledBack,
    Quarantined,
    Rejected,
    RequestUnimplemented,
}

impl SemaWriteOutput {
    pub fn route(&self) -> SemaWriteOutputRoute {
        match self {
            Self::Registered(_) => SemaWriteOutputRoute::Registered,
            Self::Allowed(_) => SemaWriteOutputRoute::Allowed,
            Self::Blocked(_) => SemaWriteOutputRoute::Blocked,
            Self::PolicyRejected(_) => SemaWriteOutputRoute::PolicyRejected,
            Self::FlipForced(_) => SemaWriteOutputRoute::FlipForced,
            Self::RolledBack(_) => SemaWriteOutputRoute::RolledBack,
            Self::Quarantined(_) => SemaWriteOutputRoute::Quarantined,
            Self::Rejected(_) => SemaWriteOutputRoute::Rejected,
            Self::RequestUnimplemented(_) => SemaWriteOutputRoute::RequestUnimplemented,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaReadOutputRoute {
    PolicyReported,
    PolicyRejected,
    RequestUnimplemented,
}

impl SemaReadOutput {
    pub fn route(&self) -> SemaReadOutputRoute {
        match self {
            Self::PolicyReported(_) => SemaReadOutputRoute::PolicyReported,
            Self::PolicyRejected(_) => SemaReadOutputRoute::PolicyRejected,
            Self::RequestUnimplemented(_) => SemaReadOutputRoute::RequestUnimplemented,
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SignalObjectName {
    Input(InputRoute),
    Output(OutputRoute),
    Started,
    Stopped,
    Admitted,
    Rejected,
    Triaged,
    Replied,
}

impl SignalObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Input(route) => match route {
                InputRoute::Register => "SignalInputRegister",
                InputRoute::Allow => "SignalInputAllow",
                InputRoute::Block => "SignalInputBlock",
                InputRoute::Query => "SignalInputQuery",
                InputRoute::ForceFlip => "SignalInputForceFlip",
                InputRoute::Rollback => "SignalInputRollback",
                InputRoute::Quarantine => "SignalInputQuarantine",
            },
            Self::Output(route) => match route {
                OutputRoute::Registered => "SignalOutputRegistered",
                OutputRoute::Allowed => "SignalOutputAllowed",
                OutputRoute::Blocked => "SignalOutputBlocked",
                OutputRoute::PolicyReported => "SignalOutputPolicyReported",
                OutputRoute::PolicyRejected => "SignalOutputPolicyRejected",
                OutputRoute::FlipForced => "SignalOutputFlipForced",
                OutputRoute::RolledBack => "SignalOutputRolledBack",
                OutputRoute::Quarantined => "SignalOutputQuarantined",
                OutputRoute::Rejected => "SignalOutputRejected",
                OutputRoute::RequestUnimplemented => "SignalOutputRequestUnimplemented",
            },
            Self::Started => "SignalStarted",
            Self::Stopped => "SignalStopped",
            Self::Admitted => "SignalAdmitted",
            Self::Rejected => "SignalRejected",
            Self::Triaged => "SignalTriaged",
            Self::Replied => "SignalReplied",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}

impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => match route {
                NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
            },
            Self::Action(route) => match route {
                NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                NexusActionRoute::Continue => "NexusActionContinue",
            },
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SemaObjectName {
    WriteInput(SemaWriteInputRoute),
    ReadInput(SemaReadInputRoute),
    WriteOutput(SemaWriteOutputRoute),
    ReadOutput(SemaReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}

impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => match route {
                SemaWriteInputRoute::Register => "SemaWriteInputRegister",
                SemaWriteInputRoute::Allow => "SemaWriteInputAllow",
                SemaWriteInputRoute::Block => "SemaWriteInputBlock",
                SemaWriteInputRoute::ForceFlip => "SemaWriteInputForceFlip",
                SemaWriteInputRoute::Rollback => "SemaWriteInputRollback",
                SemaWriteInputRoute::Quarantine => "SemaWriteInputQuarantine",
            },
            Self::ReadInput(route) => match route {
                SemaReadInputRoute::Query => "SemaReadInputQuery",
            },
            Self::WriteOutput(route) => match route {
                SemaWriteOutputRoute::Registered => "SemaWriteOutputRegistered",
                SemaWriteOutputRoute::Allowed => "SemaWriteOutputAllowed",
                SemaWriteOutputRoute::Blocked => "SemaWriteOutputBlocked",
                SemaWriteOutputRoute::PolicyRejected => "SemaWriteOutputPolicyRejected",
                SemaWriteOutputRoute::FlipForced => "SemaWriteOutputFlipForced",
                SemaWriteOutputRoute::RolledBack => "SemaWriteOutputRolledBack",
                SemaWriteOutputRoute::Quarantined => "SemaWriteOutputQuarantined",
                SemaWriteOutputRoute::Rejected => "SemaWriteOutputRejected",
                SemaWriteOutputRoute::RequestUnimplemented => "SemaWriteOutputRequestUnimplemented",
            },
            Self::ReadOutput(route) => match route {
                SemaReadOutputRoute::PolicyReported => "SemaReadOutputPolicyReported",
                SemaReadOutputRoute::PolicyRejected => "SemaReadOutputPolicyRejected",
                SemaReadOutputRoute::RequestUnimplemented => "SemaReadOutputRequestUnimplemented",
            },
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectName {
    Signal(SignalObjectName),
    Nexus(NexusObjectName),
    Sema(SemaObjectName),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct TraceEvent(pub ObjectName);

impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Signal(object_name) => object_name.name(),
            Self::Nexus(object_name) => object_name.name(),
            Self::Sema(object_name) => object_name.name(),
        }
    }
}

impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }

    pub fn object_name(&self) -> ObjectName {
        self.0
    }

    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct MessageIdentifier(pub Integer);
#[cfg(feature = "nota-text")]
impl MessageIdentifier {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct OriginRoute(pub Integer);
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum MessageRoot {
    Input,
    Output,
}

pub mod schema {
    #[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
    pub enum Plane<SignalRoot, NexusRoot, SemaRoot> {
        Signal(super::Signal<SignalRoot>),
        Nexus(super::Nexus<NexusRoot>),
        Sema(super::Sema<SemaRoot>),
    }

    impl<SignalRoot, NexusRoot, SemaRoot> Plane<SignalRoot, NexusRoot, SemaRoot> {
        pub fn origin_route(&self) -> super::OriginRoute {
            match self {
                Self::Signal(message) => message.origin_route(),
                Self::Nexus(message) => message.origin_route(),
                Self::Sema(message) => message.origin_route(),
            }
        }
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Signal<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Signal<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Signal<NextRoot> {
        Signal::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}

impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn root(&self) -> &Root {
        &self.root
    }

    pub fn into_root(self) -> Root {
        self.root
    }

    pub fn map_root<NextRoot>(self, map: impl FnOnce(Root) -> NextRoot) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSent {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub root: MessageRoot,
    pub short_header: Integer,
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageProcessed<Reply> {
    pub identifier: MessageIdentifier,
    pub origin_route: OriginRoute,
    pub reply: Reply,
}

pub trait MessageSentHook {
    type Error;

    fn message_sent(&mut self, event: MessageSent) -> Result<(), Self::Error>;
}

pub trait MessageProcessedHook<Reply> {
    type Error;

    fn message_processed(&mut self, event: MessageProcessed<Reply>) -> Result<(), Self::Error>;
}

impl MessageSent {
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageSentHook,
    {
        hook.message_sent(self.clone())
    }
}

impl<Reply> MessageProcessed<Reply> {
    pub fn new(identifier: MessageIdentifier, origin_route: OriginRoute, reply: Reply) -> Self {
        Self { identifier, origin_route, reply }
    }

    pub fn identifier(&self) -> MessageIdentifier {
        self.identifier
    }

    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }

    pub fn into_reply(self) -> Reply {
        self.reply
    }

    pub fn push_to<Hook>(&self, hook: &mut Hook) -> Result<(), Hook::Error>
    where
        Hook: MessageProcessedHook<Reply>,
        Reply: Clone,
    {
        hook.message_processed(self.clone())
    }
}

impl Input {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Input> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Input,
            short_header: self.root().short_header(),
        }
    }
}

impl Output {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> Signal<Self> {
        Signal::new(origin_route, self)
    }

}

impl signal::Signal<Output> {
    pub fn message_sent(&self, identifier: MessageIdentifier) -> MessageSent {
        MessageSent {
            identifier,
            origin_route: self.origin_route(),
            root: MessageRoot::Output,
            short_header: self.root().short_header(),
        }
    }
}

pub mod signal {
    pub type Input = super::Input;
    pub type Output = super::Output;
    pub type Signal<Root> = super::Signal<Root>;
}

pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

pub mod sema {
    pub type WriteInput = super::SemaWriteInput;
    pub type WriteOutput = super::SemaWriteOutput;
    pub type ReadInput = super::SemaReadInput;
    pub type ReadOutput = super::SemaReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

impl SemaWriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaWriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl SemaReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

impl nexus::Nexus<nexus::Work> {
    pub fn into_nexus_action(self) -> nexus::Nexus<nexus::Action> {
        let origin_route = self.origin_route();
        match self.into_root() {
            NexusWork::SignalArrived(input) => match input {
                Input::Register(payload) => NexusAction::from(SemaWriteInput::Register(payload)),
                Input::Allow(payload) => NexusAction::from(SemaWriteInput::Allow(payload)),
                Input::Block(payload) => NexusAction::from(SemaWriteInput::Block(payload)),
                Input::Query(payload) => NexusAction::from(SemaReadInput::Query(payload)),
                Input::ForceFlip(payload) => NexusAction::from(SemaWriteInput::ForceFlip(payload)),
                Input::Rollback(payload) => NexusAction::from(SemaWriteInput::Rollback(payload)),
                Input::Quarantine(payload) => NexusAction::from(SemaWriteInput::Quarantine(payload)),
            },
            NexusWork::SemaWriteCompleted(output) => match output {
                SemaWriteOutput::Registered(payload) => NexusAction::from(Output::Registered(payload)),
                SemaWriteOutput::Allowed(payload) => NexusAction::from(Output::Allowed(payload)),
                SemaWriteOutput::Blocked(payload) => NexusAction::from(Output::Blocked(payload)),
                SemaWriteOutput::PolicyRejected(payload) => NexusAction::from(Output::PolicyRejected(payload)),
                SemaWriteOutput::FlipForced(payload) => NexusAction::from(Output::FlipForced(payload)),
                SemaWriteOutput::RolledBack(payload) => NexusAction::from(Output::RolledBack(payload)),
                SemaWriteOutput::Quarantined(payload) => NexusAction::from(Output::Quarantined(payload)),
                SemaWriteOutput::Rejected(payload) => NexusAction::from(Output::Rejected(payload)),
                SemaWriteOutput::RequestUnimplemented(payload) => NexusAction::from(Output::RequestUnimplemented(payload)),
            },
            NexusWork::SemaReadCompleted(output) => match output {
                SemaReadOutput::PolicyReported(payload) => NexusAction::from(Output::PolicyReported(payload)),
                SemaReadOutput::PolicyRejected(payload) => NexusAction::from(Output::PolicyRejected(payload)),
                SemaReadOutput::RequestUnimplemented(payload) => NexusAction::from(Output::RequestUnimplemented(payload)),
            },
            _ => panic!("nexus work cannot project to a generated nexus action"),
        }
        .with_origin_route(origin_route)
    }
}

impl nexus::Nexus<nexus::Action> {
    pub fn into_sema_write_input(self) -> sema::Sema<sema::WriteInput> {
        let origin_route = self.origin_route();
        match self.into_root() {
            NexusAction::CommandSemaWrite(input) => input.with_origin_route(origin_route),
            _ => panic!("nexus action is not a SEMA write input"),
        }
    }

    pub fn into_sema_read_input(self) -> sema::Sema<sema::ReadInput> {
        let origin_route = self.origin_route();
        match self.into_root() {
            NexusAction::CommandSemaRead(input) => input.with_origin_route(origin_route),
            _ => panic!("nexus action is not a SEMA read input"),
        }
    }

    pub fn into_signal_output(self) -> signal::Signal<signal::Output> {
        let origin_route = self.origin_route();
        match self.into_root() {
            NexusAction::ReplyToSignal(output) => output.with_origin_route(origin_route),
            _ => panic!("nexus action is not a signal reply"),
        }
    }
}

impl sema::Sema<sema::WriteOutput> {
    pub fn into_nexus_work(self) -> nexus::Nexus<nexus::Work> {
        let origin_route = self.origin_route();
        NexusWork::from(self.into_root()).with_origin_route(origin_route)
    }
}

impl sema::Sema<sema::ReadOutput> {
    pub fn into_nexus_work(self) -> nexus::Nexus<nexus::Work> {
        let origin_route = self.origin_route();
        NexusWork::from(self.into_root()).with_origin_route(origin_route)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}

impl std::fmt::Display for ActorStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => write!(formatter, "actor resource busy: {message}"),
            Self::ConfigurationInvalid(message) => write!(formatter, "actor configuration invalid: {message}"),
        }
    }
}

impl std::error::Error for ActorStartFailure {}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ActorStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}

impl std::fmt::Display for ActorStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => write!(formatter, "actor resource locked: {message}"),
            Self::ChildStillRunning(message) => write!(formatter, "actor child still running: {message}"),
        }
    }
}

impl std::error::Error for ActorStopFailure {}

pub trait SignalEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_signal_activation(&self, _object_name: SignalObjectName) {}
    fn trace_signal_admitted(&self) {
        self.trace_signal_activation(SignalObjectName::Admitted);
    }
    fn trace_signal_rejected(&self) {
        self.trace_signal_activation(SignalObjectName::Rejected);
    }
    fn trace_signal_triaged(&self) {
        self.trace_signal_activation(SignalObjectName::Triaged);
    }
    fn trace_signal_replied(&self) {
        self.trace_signal_activation(SignalObjectName::Replied);
    }

    fn triage_inner(&self, input: signal::Signal<signal::Input>) -> nexus::Nexus<nexus::Work>;
    fn reply_inner(&self, output: nexus::Nexus<nexus::Action>) -> signal::Signal<signal::Output>;

    fn triage(&self, input: signal::Signal<signal::Input>) -> nexus::Nexus<nexus::Work> {
        let output = self.triage_inner(input);
        self.trace_signal_triaged();
        output
    }

    fn reply(&self, output: nexus::Nexus<nexus::Action>) -> signal::Signal<signal::Output> {
        let signal_output = self.reply_inner(output);
        self.trace_signal_replied();
        signal_output
    }
}

pub trait NexusEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }

    fn decide(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action>;

    fn execute(&mut self, input: nexus::Nexus<nexus::Work>) -> nexus::Nexus<nexus::Action> {
        self.trace_nexus_entered();
        let output = self.decide(input);
        self.trace_nexus_decided();
        output
    }
}

pub trait SemaEngine {
    fn on_start(&mut self) -> Result<(), ActorStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), ActorStopFailure> {
        Ok(())
    }

    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }

    fn apply_inner(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput>;

    fn apply(&mut self, input: sema::Sema<sema::WriteInput>) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }

    fn observe(&self, input: sema::Sema<sema::ReadInput>) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

pub trait UpgradeFrom<Previous>: Sized {
    type Error;

    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}

pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}

impl<Current, Previous> AcceptPrevious<Previous> for Current where Current: UpgradeFrom<Previous> {}
